# Configuration/Services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Cobweb\SvconnectorMobilede\:
    resource: '../Classes/*'

  Cobweb\SvconnectorMobilede\Service\ConnectorFeed:
    public: true
    arguments:
      - !tagged_iterator connector.service
